services:
  hello-world:
    build:
      context: https://github.com/7R41N33/hello-world:main
    environment:
      POSTGRES_USER: ${VOTE_APP_POSTGRES.USER}
      POSTGRES_PASSWORD: ${VOTE_APP_POSTGRES.PASSWORD}

ingress:
  service: hello-world
  port: 80
