services1:
  nginx:
    image: nginx
    secrets:
      - postgres_user
      - postgres_password

secrets:
  postgres_user:
    external: true
    name: POSTGRES_USER
  postgres_password:
    external: true
    name: POSTGRES_PASSWORD


x-uffizzi-ingress:
  service: nginx
  port: 80
