services:
  hello-world:
    build:
      context: https://github.com/7R41N33/hello-world:master
      dockerfile: Dockerfile.args
      args:
        - IMAGE_PATH=images
        - TEST_ARG="Hello from compose"

ingress:
  service: hello-world
  port: 80
