services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    configs:
      - source: vote_conf
        target: /etc/nginx/conf.d

  worker:
    image: uffizziqa.azurecr.io/example-worker:latest
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: uffizziqa.azurecr.io/example-vote:latest

  result:
    image: uffizziqa.azurecr.io/example-result:latest

configs:
  vote_conf:
    file: ./configs/vote.conf

x-uffizzi-ingress:
  service: nginx
  port: 8080

x-uffizzi-continuous-preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 10h
  share_to_github: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_image_tag_is_updated: true
