services:
  hello-world:
    build:
      context: https://github.com/7R41N33/hello-world#main1

ingress:
  service: hello-world
  port: 80

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 10h
  share_to_github: true
