services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    env_file: .env

  nginx:
    image: nginx:latest
    configs:
      - source: vote_conf
        target: /etc/nginx/conf.d/default.conf

  worker:
    build:
      context: https://github.com/7R41N33/example-voting-worker
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    build:
      context: https://github.com/7R41N33/example-voting-vote

  result:
    build:
      context: https://github.com/7R41N33/example-voting-result

configs:
  vote_conf:
    file: ./configs/vote.conf

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: true
  delete_preview_after: 10h

ingress:
  service: nginx
  port: 8080
