services:
  hello-world:
    build:
      context: infra
      dockerfile: Dockerfile

x-uffizzi-ingress:
  service: hello-world
  port: 80

x-uffizzi-continuous-preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 10h
  share_to_github: true
